baseURL = 'https://www.bcars.org/'
languageCode = 'en-us'
title = 'BCARS 2024'

[params]
    [params.editURL]
        enable = true
        base = "https://github.com/BCARS/bcarsdotorg/edit/main/content"
   [params.navbar]
        displayTitle = true
        displayLogo = true
    [params.navbar.logo]
      path = "/images/BCARS-LOGO-svg.svg"
      width = 60
      height = 60
      link = "/"
    [params.page]
        width = "wide"
    [params.footer]
        displayCopyright = true
        displayPoweredBy = false

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menus]
[[menus.main]]
    name = "Welcome"
    url = "/"
    weight = 1
[[menus.main]]
    name = "Activities"
    url = "/activities/"
    weight = 2
[[menus.main]]
    name = "Repeaters"
    url = "/repeaters/"
    weight = 3
[[menus.main]]
    name = "Field Day"
    # pageRef = "license"
    url = "/fieldday/"
    weight = 4
[[menus.main]]
    name = "Get Your License"
    # pageRef = "license"
    url = "/license/"
    weight = 3
[[menus.main]]
    name = "Search"
    params =   { "type" = "search" }
    weight = 5
[[menus.main]]
    name = "GitHub"
    url = "https://www.github.com/BCARS/bcarsdotorg"
    params = {"icon" =  "github"}
    weight = 6


[module]

    [[module.imports]]
        path = "github.com/imfing/hextra"
        disable = false

