baseURL = 'https://b2024.bcars.org/'
languageCode = 'en-us'
title = 'BCARS 2024'

# theme = 'ananke'

# [params]
# [[params.theme]]
#     # default = 'system'
#     # displayToggle = true

[menus]
[[menus.main]]
    name = "Activities"
    url = "/activities/"
    weight = 1
[[menus.main]]
    name = "Repeaters"
    url = "/repeaters/"
    # pageRef = "about"
    weight = 2
[[menus.main]]
    name = "Field Day"
    # pageRef = "license"
    url = "/fieldday/"
    weight = 3
[[menus.main]]
    name = "Get Your License"
    # pageRef = "license"
    url = "/license/"
    weight = 3
[[menus.main]]
    name = "Search"
    params =   { "type" = "search" }

[module]
    [[module.imports]]
        path = "github.com/imfing/hextra"
        disable = false

    # [[ module.imports ]]
    #     path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    #     disable = false
    # [[module.imports]]
    #     path = "github.com/colinwilson/lotusdocs"
    #     disable = false
    # [[module.imports]]
    #     path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    #     disable = false

# Change the default theme to be use when building the site with Hugo
# theme = "relearn"
# theme = "cupper-hugo-theme"

# For search functionality
# [outputs]
# home = [ "HTML", "RSS", "SEARCH"]
